version: "3.6"

services:
  db:
    image: postgres:16.1
    restart: always
    ports:
      - 5555:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd

  web:
    image: nginx
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=P@ssw0rd
